export const CHANGE_PROFILE_ITEM = 'CHANGE_PROFILE_ITEM';
export const ADD_PROFILE_ITEM = 'ADD_PROFILE_ITEM';
export const UP_PROFILE_ITEM = 'UP_PROFILE_ITEM';
export const DOWN_PROFILE_ITEM = 'DOWN_PROFILE_ITEM';
export const DELETE_PROFILE_ITEM = 'DELETE_PROFILE_ITEM';
export const RENAME_ONCHANGE = 'RENAME_ONCHANGE';
export const RENAME_HANDLER = 'RENAME_HANDLER';

export const OPEN_DELETE_POPUP = 'OPEN_DELETE_POPUP';
export const CLOSE_DELETE_POPUP = 'CLOSE_DELETE_POPUP';
export const OPEN_EDIT_POPUP = 'OPEN_EDIT_POPUP';
export const CLOSE_EDIT_POPUP = 'CLOSE_EDIT_POPUP';

/*
 * action creators
 */
